# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Filipin.eu
author:
  name: Željko Filipin
  email: "zeljko.filipin@gmail.com"
description: Željko Filipin's blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://filipin.eu/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# GitHub Pages
# Minima's v3 dark theme doesn't work without this and
# - jekyll-remote-theme
remote_theme: jekyll/minima@7a326eb6df07ee6ee5305cfc1b28f7092037e67d

# Custom settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:title

collections:
  tags:
    output: true

# Minima https://github.com/jekyll/minima
theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: dark
  social_links:
    twitter: zeljkofilipin
    github: zeljkofilipin
    stackoverflow: "17469"
    facebook: zeljko.filipin
    linkedin: zeljkofilipin

## Disqus
disqus:
  shortname: filipineu

## Google
google_analytics: UA-200958-28
